---
# Source: solr-external/charts/solr/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr-catplus
  labels:
    app.kubernetes.io/instance: solr-catplus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: 9.8.0
    helm.sh/chart: solr-9.5.3
    app.kubernetes.io/component: solr
  namespace: "default"
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: solr-catplus
      app.kubernetes.io/name: solr
      app.kubernetes.io/component: solr
  serviceName: solr-catplus-headless
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/instance: solr-catplus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: solr
        app.kubernetes.io/version: 9.8.0
        helm.sh/chart: solr-9.5.3
        app.kubernetes.io/component: solr
    spec:
      serviceAccountName: solr-catplus
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: solr-catplus
                    app.kubernetes.io/name: solr
                    app.kubernetes.io/component: solr
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      enableServiceLinks: true
      initContainers:
        - name: prepare-server-dir
          image: docker.io/bitnami/solr:9.8.0-debian-12-r1
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 3
              memory: 2048Mi
            requests:
              cpu: 2
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash

              . /opt/bitnami/scripts/liblog.sh

              info "Copying server dir to empty dir"
              # In order to not break the application functionality (such as upgrades or plugins) we need
              # to make the base directory writable, so we need to copy it to an empty dir volume
              cp -r --preserve=mode /opt/bitnami/solr/server /emptydir/app-server-dir

              info "Copy operation completed"
          volumeMounts:
            - name: empty-dir
              mountPath: /emptydir
      containers:
        - name: solr
          image: docker.io/bitnami/solr:9.8.0-debian-12-r1
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - /scripts/setup.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SOLR_ENABLE_CLOUD_MODE
              value: "no"
            - name: SOLR_NUMBER_OF_NODES
              value: "1"
            - name: SOLR_PORT_NUMBER
              value: "8983"
            - name: SOLR_SERVER_DIRECTORY
              value: "server"
            - name: SOLR_CORES
              value: "my-core"
            - name: SOLR_COLLECTION_SHARDS
              value: "1"
            - name: SOLR_COLLECTION_REPLICAS
              value: "2"
            - name: SOLR_ENABLE_AUTHENTICATION
              value: "no"
            - name: SOLR_ZK_HOSTS
              value: "solr-catplus-zookeeper-0.solr-catplus-zookeeper-headless.default.svc.cluster.local:2181,solr-catplus-zookeeper-1.solr-catplus-zookeeper-headless.default.svc.cluster.local:2181,solr-catplus-zookeeper-2.solr-catplus-zookeeper-headless.default.svc.cluster.local:2181"
          ports:
            - name: http
              containerPort: 8983
          resources:
            limits:
              cpu: 3
              memory: 2048Mi
            requests:
              cpu: 2
              memory: 512Mi
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 40
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                curl --silent --connect-timeout 15000  http://localhost:${SOLR_PORT_NUMBER}/solr/admin/info/system | grep --quiet  '\"status\":0'
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                curl --silent --connect-timeout 15000  http://localhost:${SOLR_PORT_NUMBER}/api/node/health | grep --quiet  '\"status\":\"OK\"'
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/server
              subPath: app-server-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/logs
              subPath: app-logs-dir
            - name: empty-dir
              mountPath: /opt/bitnami/solr/tmp
              subPath: app-tmp-dir
            - name: scripts
              mountPath: /scripts/setup.sh
              subPath: setup.sh
            - name: data
              mountPath: /bitnami/solr
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: scripts
          configMap:
            name: solr-catplus-scripts
            defaultMode: 0755
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        annotations:
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
