---
# Source: solr/charts/zookeeper/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: solr-zookeeper-headless
  namespace: default
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 3.9.3
    helm.sh/chart: zookeeper-13.7.2
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-client
      port: 2181
      targetPort: client
    - name: tcp-follower
      port: 2888
      targetPort: follower
    - name: tcp-election
      port: 3888
      targetPort: election
  selector:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: zookeeper
