apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - "https://github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.9.5"
  - "https://github.com/argoproj/argo-events/manifests/extensions/validating-webhook?ref=v1.9.5"
  - ./eventbus.yaml
namespace: argo-events
